apiVersion: v1
kind: Service
metadata:
  name: intothepaddock
  namespace: intothepaddock
spec:
  type: ClusterIP
  selector:
    app: intothepaddock
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
